[2025-10-01 23:02:12,995: INFO: test: Welcome to our custom log]
[2025-10-01 23:03:17,485: INFO: test: Welcome to our custom log]
[2025-10-01 23:25:02,548: INFO: test: Welcome to our custom log]
[2025-10-01 23:25:20,033: INFO: test: Welcome to our custom log]
[2025-10-03 01:58:01,115: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-03 01:58:01,116: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-03 01:58:01,117: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-03 01:58:01,117: INFO: common: created directory at: artifacts]
[2025-10-03 01:58:01,117: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-03 01:58:01,117: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_url']
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipleine/stage01_dataingestion.py", line 10, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/config/configuration.py", line 26, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_url'
[2025-10-03 01:59:09,912: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-03 01:59:09,913: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-03 01:59:09,913: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-03 01:59:09,913: INFO: common: created directory at: artifacts]
[2025-10-03 01:59:09,913: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-03 01:59:09,913: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_url']
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipleine/stage01_dataingestion.py", line 10, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/config/configuration.py", line 26, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_url'
[2025-10-03 02:02:57,595: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-03 02:02:57,597: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-03 02:02:57,598: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-03 02:02:57,598: INFO: common: created directory at: artifacts]
[2025-10-03 02:02:57,598: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-03 02:02:57,599: ERROR: main: "'ConfigBox' object has no attribute 'source_url'"]
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'source_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'source_url'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'source_url'. Did you mean: 'source_URL'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'source_url'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'source_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'source_url'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'source_url'. Did you mean: 'source_URL'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipleine/stage01_dataingestion.py", line 10, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/config/configuration.py", line 28, in get_data_ingestion_config
    source_url=config.source_url,
               ^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'source_url'". Did you mean: 'source_URL'?
[2025-10-03 02:03:25,752: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-03 02:03:25,753: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-03 02:03:25,754: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-03 02:03:25,754: INFO: common: created directory at: artifacts]
[2025-10-03 02:03:25,754: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-03 02:03:25,755: ERROR: main: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_url']
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipleine/stage01_dataingestion.py", line 10, in main
    data_ingestion_config = config.get_data_ingestion_config()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/config/configuration.py", line 26, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: DataIngestionConfig.__init__() got an unexpected keyword argument 'source_url'
[2025-10-03 02:05:44,020: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-03 02:05:44,021: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-03 02:05:44,022: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-03 02:05:44,022: INFO: common: created directory at: artifacts]
[2025-10-03 02:05:44,022: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-03 02:05:44,022: INFO: data_ingestion: Trying to download file...]
[2025-10-03 02:05:44,022: INFO: data_ingestion: Download started...]
[2025-10-03 02:05:44,022: ERROR: main: 'DataIngestionConfig' object has no attribute 'source_URL']
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipleine/stage01_dataingestion.py", line 12, in main
    data_ingestion.download_file()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/components/data_ingestion.py", line 21, in download_file
    url=self.config.source_URL,
        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestionConfig' object has no attribute 'source_URL'. Did you mean: 'source_url'?
[2025-10-03 02:07:24,933: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-03 02:07:24,934: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-03 02:07:24,934: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-03 02:07:24,935: INFO: common: created directory at: artifacts]
[2025-10-03 02:07:24,935: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-03 02:07:24,935: INFO: data_ingestion: Trying to download file...]
[2025-10-03 02:07:24,935: INFO: data_ingestion: Download started...]
[2025-10-03 02:07:39,612: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 09CA:A53F8:576ED:D535E:68DEE284
Accept-Ranges: bytes
Date: Thu, 02 Oct 2025 20:37:27 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210052-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1759437446.676096,VS0,VE2106
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 15de6ff23ab3ddaf775b42466c6f8c30b7b3b28c
Expires: Thu, 02 Oct 2025 20:42:27 GMT
Source-Age: 2

]
[2025-10-03 02:07:39,612: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-03 02:07:39,652: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-03 02:07:39,689: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-03 02:32:55,336: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-03 02:32:55,338: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-03 02:32:55,338: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-03 02:32:55,339: INFO: common: created directory at: artifacts]
[2025-10-03 02:32:55,339: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-03 02:32:55,339: INFO: data_ingestion: Trying to download file...]
[2025-10-03 02:32:55,339: INFO: data_ingestion: Download started...]
[2025-10-03 02:33:04,525: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 09CA:A53F8:576ED:D535E:68DEE284
Accept-Ranges: bytes
Date: Thu, 02 Oct 2025 21:02:56 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210071-BOM
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1759438976.122453,VS0,VE311
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: fee1c571b60d4a0ebf934acd2d2ec6c1617ec0d1
Expires: Thu, 02 Oct 2025 21:07:56 GMT
Source-Age: 0

]
[2025-10-03 02:33:04,525: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-03 02:33:04,594: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-03 02:33:04,666: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 15:53:45,637: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 15:53:45,639: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 15:53:45,641: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 15:53:45,641: INFO: common: created directory at: artifacts]
[2025-10-07 15:53:45,642: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 15:53:45,642: INFO: data_ingestion: Trying to download file...]
[2025-10-07 15:53:45,642: INFO: data_ingestion: Download started...]
[2025-10-07 15:53:55,989: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C496:2B950E:1485A5:2E53DB:68E4EA31
Accept-Ranges: bytes
Date: Tue, 07 Oct 2025 10:23:48 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210052-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1759832627.527423,VS0,VE1987
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8ac143e5f99976cb347c096509495fb3d23721a7
Expires: Tue, 07 Oct 2025 10:28:48 GMT
Source-Age: 2

]
[2025-10-07 15:53:55,989: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 15:53:56,055: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 15:53:56,126: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 15:53:56,126: INFO: main: ******************************]
[2025-10-07 15:53:56,126: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 15:53:56,126: ERROR: main: name 'PrepareBaseModelTrainingPipelines' is not defined]
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 23, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipelines()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'PrepareBaseModelTrainingPipelines' is not defined. Did you mean: 'PrepareBaseModelTrainingPipeline'?
[2025-10-07 15:54:28,593: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 15:54:28,594: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 15:54:28,596: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 15:54:28,596: INFO: common: created directory at: artifacts]
[2025-10-07 15:54:28,596: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 15:54:28,596: INFO: data_ingestion: Trying to download file...]
[2025-10-07 15:54:28,597: INFO: data_ingestion: File already exists of size: ~ 21806 KB]
[2025-10-07 15:54:28,597: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 15:54:28,603: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 15:54:28,606: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 15:54:28,606: INFO: main: ******************************]
[2025-10-07 15:54:28,606: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 15:54:28,607: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 15:54:28,609: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 15:54:28,609: INFO: common: created directory at: artifacts]
[2025-10-07 15:54:28,610: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 15:54:28,611: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 15:54:28,612: INFO: common: created directory at: artifacts]
[2025-10-07 15:54:28,612: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 15:54:29,080: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-10-07 15:54:29,271: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-10-07 15:54:29,424: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 16:56:25,441: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 16:56:25,453: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 16:56:25,455: INFO: common: created directory at: artifacts]
[2025-10-07 16:56:25,456: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 16:56:25,457: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:12:39,630: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:12:39,642: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:12:39,643: INFO: common: created directory at: artifacts]
[2025-10-07 17:12:39,644: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:12:39,645: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:12:39,646: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:12:40,086: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:14:16,443: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:14:16,447: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:14:16,448: INFO: common: created directory at: artifacts]
[2025-10-07 17:14:16,449: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:14:16,450: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:14:16,451: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:14:16,749: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:15:47,209: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:15:47,211: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:15:47,212: INFO: common: created directory at: artifacts]
[2025-10-07 17:15:47,214: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:15:47,215: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:15:47,216: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:15:47,507: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:16:31,481: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:16:31,484: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:16:31,485: INFO: common: created directory at: artifacts]
[2025-10-07 17:16:31,485: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:16:31,487: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:16:31,488: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:16:32,140: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:20:16,595: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:20:16,598: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:20:16,600: INFO: common: created directory at: artifacts]
[2025-10-07 17:20:16,600: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:20:16,601: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:20:16,602: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:20:17,297: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:24:32,510: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:24:32,513: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:24:32,514: INFO: common: created directory at: artifacts]
[2025-10-07 17:24:32,515: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:24:32,516: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:24:32,517: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:24:33,230: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:26:40,212: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:26:40,215: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:26:40,216: INFO: common: created directory at: artifacts]
[2025-10-07 17:26:40,218: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:26:40,218: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:26:40,219: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:26:40,798: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:26:58,580: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:26:58,583: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:26:58,584: INFO: common: created directory at: artifacts]
[2025-10-07 17:26:58,585: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:26:58,585: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:26:58,587: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:26:59,277: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:49:05,851: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 17:49:05,861: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:49:05,861: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:49:05,862: INFO: common: created directory at: artifacts]
[2025-10-07 17:49:05,862: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 17:49:05,862: INFO: data_ingestion: Trying to download file...]
[2025-10-07 17:49:05,862: INFO: data_ingestion: Download started...]
[2025-10-07 17:49:15,241: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: B0A0:2A7365:17F9BE:34586A:68E50539
Accept-Ranges: bytes
Date: Tue, 07 Oct 2025 12:19:08 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210078-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1759839547.650177,VS0,VE2009
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 2b723a20368aea3de8ef806f06611852045492c1
Expires: Tue, 07 Oct 2025 12:24:08 GMT
Source-Age: 2

]
[2025-10-07 17:49:15,241: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 17:49:15,278: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 17:49:15,309: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 17:49:15,309: INFO: main: ******************************]
[2025-10-07 17:49:15,310: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 17:49:15,311: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:49:15,311: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:49:15,311: INFO: common: created directory at: artifacts]
[2025-10-07 17:49:15,312: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:49:15,313: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:49:15,313: INFO: common: created directory at: artifacts]
[2025-10-07 17:49:15,313: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 17:49:15,598: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-10-07 17:49:15,704: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-10-07 17:49:15,790: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 17:49:15,791: INFO: main: ******************************]
[2025-10-07 17:49:15,791: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 17:49:15,792: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:49:15,792: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:49:15,793: INFO: common: created directory at: artifacts]
[2025-10-07 17:49:15,793: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:49:15,793: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:49:15,793: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:49:15,918: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:49:16,394: ERROR: main: numpy() is only available when eager execution is enabled.]
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 39, in <module>
    prepare_base_model.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipeline/stage03_training.py", line 20, in main
    training.train(
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/components/training.py", line 67, in train
    self.model.fit(
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/keras/src/backend/tensorflow/core.py", line 171, in convert_to_numpy
    return np.array(x)
           ^^^^^^^^^^^
NotImplementedError: numpy() is only available when eager execution is enabled.
[2025-10-07 17:56:47,024: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 17:56:47,026: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:56:47,026: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:56:47,026: INFO: common: created directory at: artifacts]
[2025-10-07 17:56:47,027: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 17:56:47,027: INFO: data_ingestion: Trying to download file...]
[2025-10-07 17:56:47,027: INFO: data_ingestion: File already exists of size: ~ 21806 KB]
[2025-10-07 17:56:47,027: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 17:56:47,030: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 17:56:47,032: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 17:56:47,032: INFO: main: ******************************]
[2025-10-07 17:56:47,032: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 17:56:47,033: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:56:47,034: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:56:47,034: INFO: common: created directory at: artifacts]
[2025-10-07 17:56:47,035: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:56:47,035: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:56:47,036: INFO: common: created directory at: artifacts]
[2025-10-07 17:56:47,036: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 17:56:47,271: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-10-07 17:56:47,419: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-10-07 17:56:47,542: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 17:56:47,542: INFO: main: ******************************]
[2025-10-07 17:56:47,543: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 17:56:47,544: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 17:56:47,544: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 17:56:47,544: INFO: common: created directory at: artifacts]
[2025-10-07 17:56:47,545: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 17:56:47,545: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 17:56:47,545: INFO: common: created directory at: artifacts/training]
[2025-10-07 17:56:47,659: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 17:56:48,121: ERROR: main: numpy() is only available when eager execution is enabled.]
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 39, in <module>
    prepare_base_model.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipeline/stage03_training.py", line 20, in main
    training.train(
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/components/training.py", line 67, in train
    self.model.fit(
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/keras/src/backend/tensorflow/core.py", line 171, in convert_to_numpy
    return np.array(x)
           ^^^^^^^^^^^
NotImplementedError: numpy() is only available when eager execution is enabled.
[2025-10-07 18:01:14,527: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:01:14,528: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:01:14,529: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:01:14,529: INFO: common: created directory at: artifacts]
[2025-10-07 18:01:14,529: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:01:14,529: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:01:14,529: INFO: data_ingestion: File already exists of size: ~ 21806 KB]
[2025-10-07 18:01:14,529: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 18:01:14,533: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 18:01:14,534: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 18:01:14,534: INFO: main: ******************************]
[2025-10-07 18:01:14,534: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 18:01:14,535: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:01:14,536: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:01:14,536: INFO: common: created directory at: artifacts]
[2025-10-07 18:01:14,537: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:01:14,538: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:01:14,538: INFO: common: created directory at: artifacts]
[2025-10-07 18:01:14,538: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 18:01:14,776: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-10-07 18:01:14,923: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-10-07 18:01:15,049: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 18:01:15,049: INFO: main: ******************************]
[2025-10-07 18:01:15,050: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 18:01:15,051: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:01:15,051: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:01:15,051: INFO: common: created directory at: artifacts]
[2025-10-07 18:01:15,051: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:01:15,052: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:01:15,052: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:01:15,184: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-07 18:01:15,641: ERROR: main: numpy() is only available when eager execution is enabled.]
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 39, in <module>
    prepare_base_model.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipeline/stage03_training.py", line 20, in main
    training.train(
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/components/training.py", line 67, in train
    self.model.fit(
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/michu/Desktop/dlendtoend/DL_PRak/venv/lib/python3.12/site-packages/keras/src/backend/tensorflow/core.py", line 171, in convert_to_numpy
    return np.array(x)
           ^^^^^^^^^^^
NotImplementedError: numpy() is only available when eager execution is enabled.
[2025-10-07 18:03:29,747: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:03:29,748: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:03:29,749: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:03:29,749: INFO: common: created directory at: artifacts]
[2025-10-07 18:03:29,749: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:03:29,749: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:03:29,749: INFO: data_ingestion: File already exists of size: ~ 21806 KB]
[2025-10-07 18:03:29,749: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 18:03:29,753: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 18:03:29,754: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 18:03:29,754: INFO: main: ******************************]
[2025-10-07 18:03:29,754: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 18:03:29,755: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:03:29,756: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:03:29,756: INFO: common: created directory at: artifacts]
[2025-10-07 18:03:29,757: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:03:29,758: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:03:29,758: INFO: common: created directory at: artifacts]
[2025-10-07 18:03:29,758: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 18:03:30,299: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 18:03:30,299: INFO: main: ******************************]
[2025-10-07 18:03:30,299: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 18:03:30,300: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:03:30,301: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:03:30,301: INFO: common: created directory at: artifacts]
[2025-10-07 18:03:30,301: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:03:30,301: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:03:30,301: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:04:02,391: INFO: main: >>>>>>>> Training completed <<<<<<]
[2025-10-07 18:16:55,799: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:16:55,801: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:16:55,802: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:16:55,802: INFO: common: created directory at: artifacts]
[2025-10-07 18:16:55,803: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:16:55,803: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:16:55,803: INFO: data_ingestion: Download started...]
[2025-10-07 18:17:13,025: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: B0A0:2A7365:17F9BE:34586A:68E50539
Accept-Ranges: bytes
Date: Tue, 07 Oct 2025 12:46:57 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210078-BOM
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1759841217.001986,VS0,VE320
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 4073670830063253894453083dc979ba8e1212a6
Expires: Tue, 07 Oct 2025 12:51:57 GMT
Source-Age: 0

]
[2025-10-07 18:17:13,025: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 18:17:13,068: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 18:17:13,100: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 18:17:13,100: INFO: main: ******************************]
[2025-10-07 18:17:13,100: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 18:17:13,101: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:17:13,102: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:17:13,102: INFO: common: created directory at: artifacts]
[2025-10-07 18:17:13,103: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:17:13,103: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:17:13,103: INFO: common: created directory at: artifacts]
[2025-10-07 18:17:13,104: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 18:17:13,664: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 18:17:13,664: INFO: main: ******************************]
[2025-10-07 18:17:13,664: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 18:17:13,665: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:17:13,666: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:17:13,666: INFO: common: created directory at: artifacts]
[2025-10-07 18:17:13,666: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:17:13,666: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:17:13,666: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:17:45,860: INFO: main: >>>>>>>> Training completed <<<<<<]
[2025-10-07 18:17:45,860: INFO: main: ******************************]
[2025-10-07 18:17:45,860: INFO: main: >>>>>>> stage evaluation start <<<<<<]
[2025-10-07 18:17:45,861: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:17:45,862: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:17:45,862: INFO: common: created directory at: artifacts]
[2025-10-07 18:17:45,862: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:17:45,862: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:17:45,863: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:18:18,884: INFO: main: >>>>>>>> evaluation completed <<<<<<]
[2025-10-07 18:25:44,918: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:25:44,919: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:25:44,920: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:25:44,920: INFO: common: created directory at: artifacts]
[2025-10-07 18:25:44,920: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:25:44,920: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:25:44,920: INFO: data_ingestion: Download started...]
[2025-10-07 18:25:55,836: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: B0A0:2A7365:17F9BE:34586A:68E50539
Accept-Ranges: bytes
Date: Tue, 07 Oct 2025 12:55:47 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210027-BOM
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1759841748.634216,VS0,VE295
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: df579efa1fef25b8c3d4698a66e9771e7e9d56a5
Expires: Tue, 07 Oct 2025 13:00:47 GMT
Source-Age: 0

]
[2025-10-07 18:25:55,836: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 18:25:55,872: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 18:25:55,903: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 18:25:55,903: INFO: main: ******************************]
[2025-10-07 18:25:55,903: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 18:25:55,904: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:25:55,905: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:25:55,905: INFO: common: created directory at: artifacts]
[2025-10-07 18:25:55,906: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:25:55,907: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:25:55,907: INFO: common: created directory at: artifacts]
[2025-10-07 18:25:55,907: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 18:25:56,459: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 18:25:56,459: INFO: main: ******************************]
[2025-10-07 18:25:56,459: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 18:25:56,460: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:25:56,461: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:25:56,461: INFO: common: created directory at: artifacts]
[2025-10-07 18:25:56,461: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:25:56,462: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:25:56,462: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:26:23,025: INFO: main: >>>>>>>> Training completed <<<<<<]
[2025-10-07 18:26:23,025: INFO: main: ******************************]
[2025-10-07 18:26:23,025: INFO: main: >>>>>>> stage evaluation start <<<<<<]
[2025-10-07 18:26:23,026: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:26:23,027: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:26:23,027: INFO: common: created directory at: artifacts]
[2025-10-07 18:26:23,027: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:26:23,027: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:26:23,027: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:26:50,222: INFO: main: >>>>>>>> evaluation completed <<<<<<]
[2025-10-07 18:30:46,719: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:30:46,720: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:30:46,721: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:30:46,721: INFO: common: created directory at: artifacts]
[2025-10-07 18:30:46,721: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:30:46,721: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:30:46,722: INFO: data_ingestion: Download started...]
[2025-10-07 18:30:46,722: ERROR: main: 'DataIngestionConfig' object has no attribute 'source_URL']
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 13, in <module>
    data_ingestion.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipeline/stage01_dataingestion.py", line 12, in main
    data_ingestion.download_file()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/components/data_ingestion.py", line 21, in download_file
    url=self.config.source_URL,
        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestionConfig' object has no attribute 'source_URL'. Did you mean: 'source_url'?
[2025-10-07 18:31:07,035: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:31:07,036: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:31:07,037: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:31:07,037: INFO: common: created directory at: artifacts]
[2025-10-07 18:31:07,037: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:31:07,037: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:31:07,037: INFO: data_ingestion: Download started...]
[2025-10-07 18:31:07,037: ERROR: main: 'DataIngestionConfig' object has no attribute 'source_URL']
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 13, in <module>
    data_ingestion.main()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipeline/stage01_dataingestion.py", line 12, in main
    data_ingestion.download_file()
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/components/data_ingestion.py", line 21, in download_file
    url=self.config.source_URL,
        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataIngestionConfig' object has no attribute 'source_URL'. Did you mean: 'source_url'?
[2025-10-07 18:31:17,718: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:31:17,720: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:31:17,721: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:31:17,721: INFO: common: created directory at: artifacts]
[2025-10-07 18:31:17,721: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:31:17,721: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:31:17,721: INFO: data_ingestion: Download started...]
[2025-10-07 18:31:28,033: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: E73C:2AFB49:190B47:364CD2:68E50F1E
Accept-Ranges: bytes
Date: Tue, 07 Oct 2025 13:01:20 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210070-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1759842079.900354,VS0,VE2029
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 28f1944c3180e6c864c865347ec7caad1b0d3f9d
Expires: Tue, 07 Oct 2025 13:06:20 GMT
Source-Age: 2

]
[2025-10-07 18:31:28,033: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 18:31:28,069: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 18:31:28,102: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 18:31:28,102: INFO: main: ******************************]
[2025-10-07 18:31:28,102: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 18:31:28,103: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:31:28,104: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:31:28,104: INFO: common: created directory at: artifacts]
[2025-10-07 18:31:28,105: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:31:28,106: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:31:28,106: INFO: common: created directory at: artifacts]
[2025-10-07 18:31:28,106: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 18:31:28,700: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 18:31:28,700: INFO: main: ******************************]
[2025-10-07 18:31:28,700: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 18:31:28,702: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:31:28,702: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:31:28,702: INFO: common: created directory at: artifacts]
[2025-10-07 18:31:28,703: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:31:28,703: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:31:28,703: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:31:56,004: INFO: main: >>>>>>>> Training completed <<<<<<]
[2025-10-07 18:31:56,004: INFO: main: ******************************]
[2025-10-07 18:31:56,004: INFO: main: >>>>>>> stage evaluation start <<<<<<]
[2025-10-07 18:31:56,005: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:31:56,006: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:31:56,006: INFO: common: created directory at: artifacts]
[2025-10-07 18:31:56,006: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:31:56,006: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:31:56,006: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:32:23,357: INFO: main: >>>>>>>> evaluation completed <<<<<<]
[2025-10-07 18:33:58,538: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:33:58,540: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:33:58,540: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:33:58,541: INFO: common: created directory at: artifacts]
[2025-10-07 18:33:58,541: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:33:58,541: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:33:58,541: INFO: data_ingestion: Download started...]
[2025-10-07 18:34:06,158: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: E73C:2AFB49:190B47:364CD2:68E50F1E
Accept-Ranges: bytes
Date: Tue, 07 Oct 2025 13:04:00 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210052-BOM
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1759842240.040517,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 67e021fbcd69bba4eee10ad532d1f275b07986de
Expires: Tue, 07 Oct 2025 13:09:00 GMT
Source-Age: 161

]
[2025-10-07 18:34:06,159: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 18:34:06,192: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 18:34:06,223: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 18:34:06,223: INFO: main: ******************************]
[2025-10-07 18:34:06,223: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 18:34:06,224: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:34:06,225: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:34:06,225: INFO: common: created directory at: artifacts]
[2025-10-07 18:34:06,226: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:34:06,227: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:34:06,227: INFO: common: created directory at: artifacts]
[2025-10-07 18:34:06,227: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 18:34:06,773: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 18:34:06,773: INFO: main: ******************************]
[2025-10-07 18:34:06,773: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 18:34:06,774: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:34:06,775: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:34:06,775: INFO: common: created directory at: artifacts]
[2025-10-07 18:34:06,775: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:34:06,775: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:34:06,776: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:34:32,793: INFO: main: >>>>>>>> Training completed <<<<<<]
[2025-10-07 18:34:32,793: INFO: main: ******************************]
[2025-10-07 18:34:32,793: INFO: main: >>>>>>> stage evaluation start <<<<<<]
[2025-10-07 18:34:32,793: ERROR: main: Evaluation.__init__() missing 1 required positional argument: 'config']
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/DL_PRak/main.py", line 53, in <module>
    model_evalutaion = Evaluation()
                       ^^^^^^^^^^^^
TypeError: Evaluation.__init__() missing 1 required positional argument: 'config'
[2025-10-07 18:39:40,066: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:39:40,068: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:39:40,068: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:39:40,069: INFO: common: created directory at: artifacts]
[2025-10-07 18:39:40,069: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:39:40,069: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:39:40,069: INFO: data_ingestion: Download started...]
[2025-10-07 18:39:57,174: INFO: main: >>>>>>> stage data ingestion stage start <<<<<<]
[2025-10-07 18:39:57,175: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:39:57,176: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:39:57,176: INFO: common: created directory at: artifacts]
[2025-10-07 18:39:57,176: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-07 18:39:57,176: INFO: data_ingestion: Trying to download file...]
[2025-10-07 18:39:57,176: INFO: data_ingestion: Download started...]
[2025-10-07 18:40:07,329: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 22329406
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "e33c4dcc8f22340234fac4b9da4a20b304912be521f658008139809163a077ea"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: E73C:2AFB49:190B47:364CD2:68E50F1E
Accept-Ranges: bytes
Date: Tue, 07 Oct 2025 13:09:57 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210053-BOM
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1759842598.744842,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 03e60a6e9be08d30eb96a7bbaae0de44c42fac98
Expires: Tue, 07 Oct 2025 13:14:57 GMT
Source-Age: 16

]
[2025-10-07 18:40:07,329: INFO: data_ingestion: unzipping file and removing unawanted files]
[2025-10-07 18:40:07,366: INFO: data_ingestion: removing file:artifacts/data_ingestion/PetImages/Dog/11702.jpg of size: ~ 0 KB]
[2025-10-07 18:40:07,398: INFO: main: >>>>>>>> data ingestion stage completed <<<<<<]
[2025-10-07 18:40:07,398: INFO: main: ******************************]
[2025-10-07 18:40:07,398: INFO: main: >>>>>>> stage Prepare base model start <<<<<<]
[2025-10-07 18:40:07,399: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:40:07,400: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:40:07,400: INFO: common: created directory at: artifacts]
[2025-10-07 18:40:07,401: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:40:07,402: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:40:07,402: INFO: common: created directory at: artifacts]
[2025-10-07 18:40:07,402: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-07 18:40:07,917: INFO: main: >>>>>>>> Prepare base model completed <<<<<<]
[2025-10-07 18:40:07,917: INFO: main: ******************************]
[2025-10-07 18:40:07,917: INFO: main: >>>>>>> stage Training start <<<<<<]
[2025-10-07 18:40:07,918: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:40:07,919: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:40:07,919: INFO: common: created directory at: artifacts]
[2025-10-07 18:40:07,919: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:40:07,919: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:40:07,919: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:40:33,973: INFO: main: >>>>>>>> Training completed <<<<<<]
[2025-10-07 18:40:33,973: INFO: main: ******************************]
[2025-10-07 18:40:33,973: INFO: main: >>>>>>> stage evaluation start <<<<<<]
[2025-10-07 18:40:33,975: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-10-07 18:40:33,975: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-07 18:40:33,975: INFO: common: created directory at: artifacts]
[2025-10-07 18:40:33,976: INFO: common: created directory at: artifacts/prepare_callbacks/checkpoint_dir]
[2025-10-07 18:40:33,976: INFO: common: created directory at: artifacts/prepare_callbacks/tensorboard_log_dir]
[2025-10-07 18:40:33,976: INFO: common: created directory at: artifacts/training]
[2025-10-07 18:41:00,047: INFO: main: >>>>>>>> evaluation completed <<<<<<]
[2025-10-07 21:32:50,296: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.169.103.28:8080]
[2025-10-07 21:32:50,296: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-10-07 21:33:13,655: INFO: _internal: 127.0.0.1 - - [07/Oct/2025 21:33:13] "GET / HTTP/1.1" 200 -]
[2025-10-07 21:33:54,249: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/app.py", line 39, in predictRoute
    result = clApp.classifier.predictiondogcat()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/DL_PRak/src/DL_PRak/pipeline/prediction.py", line 12, in predictiondogcat
    model = load_model(os.path.join("artifacts","training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/keras/src/saving/saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 118, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/h5py/_hl/files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michu/Desktop/dlendtoend/.venv/lib/python3.12/site-packages/h5py/_hl/files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'artifacts/training/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-10-07 21:33:54,261: INFO: _internal: 127.0.0.1 - - [07/Oct/2025 21:33:54] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-10-07 21:36:16,479: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.169.103.28:8080]
[2025-10-07 21:36:16,479: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-10-07 21:36:21,101: INFO: _internal: 127.0.0.1 - - [07/Oct/2025 21:36:21] "GET / HTTP/1.1" 200 -]
[2025-10-07 21:36:29,476: INFO: _internal: 127.0.0.1 - - [07/Oct/2025 21:36:29] "POST /predict HTTP/1.1" 200 -]
[2025-10-07 21:36:58,633: INFO: _internal: 127.0.0.1 - - [07/Oct/2025 21:36:58] "POST /predict HTTP/1.1" 200 -]
[2025-10-07 21:44:32,843: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.169.103.28:8080]
[2025-10-07 21:44:32,843: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-10-07 21:44:36,541: INFO: _internal: 127.0.0.1 - - [07/Oct/2025 21:44:36] "GET / HTTP/1.1" 200 -]
[2025-10-07 21:44:36,672: INFO: _internal: 127.0.0.1 - - [07/Oct/2025 21:44:36] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-10-07 21:45:14,639: INFO: _internal: 127.0.0.1 - - [07/Oct/2025 21:45:14] "POST /predict HTTP/1.1" 200 -]
